let product = {
  id: "",
  ProductType: "Jacket",
  productSize: "S",
  productMaterial: "",
  productGender: "",
  productPrice: 1,
  favorite: false,
  new: false,
  quantity: 1,
  availableColors: [],
  productImages: [],
};

const products = [
  {
    id: "",
    ProductType: "Jacket",
    productSize: "S",
    productMaterial: "",
    productGender: "",
    productPrice: 1,
    favorite: false,
    new: false,
    quantity: 1,
    availableColors: [],
    productImages: [],
  },
  {
    id: "",
    ProductType: "Jacket",
    productSize: "S",
    productMaterial: "",
    productGender: "",
    productPrice: 1,
    favorite: false,
    new: false,
    quantity: 1,
    availableColors: [],
    productImages: [],
  },
  {
    id: "",
    ProductType: "Jacket",
    productSize: "S",
    productMaterial: "",
    productGender: "",
    productPrice: 1,
    favorite: false,
    new: false,
    quantity: 1,
    availableColors: [],
    productImages: [],
  },
];

const FavoriteItems = [];
